# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

conda:
    environment: environment.yml

build:
  os: ubuntu-20.04
  tools:
    python: "miniconda3-4.7"
    nodejs: "18" 
  jobs:
    post_install:
      # Install dependencies defined in your ``package.json``
      - npm
      # Install any other extra dependencies to build the docs
      - npm install -g jsdoc 
# Build documentation in the docs/ directory with Sphinx
sphinx:
   builder: html
   configuration: docs/conf.py


